### ISSUE TITLE
joey_issue

### ISSUE THREAD

**Issue by yoghurtpowerbear** [tanin-t/web-dev-tutorial-for-ez#5]
1. เพิ่มกำลังใน data base 
2. พอmigrateมันerror
```powershell
PS C:\Users\HP\OneDrive\Documents\django-joey> cd mysite
PS C:\Users\HP\OneDrive\Documents\django-joey\mysite> py manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, bill, contenttypes, sessions
Running migrations:
  Applying bill.0007_auto_20210422_0041...Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Python\Python38\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Python\Python38\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Python\Python38\lib\site-packages\django\core\management\base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Python\Python38\lib\site-packages\django\core\management\base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "C:\Python\Python38\lib\site-packages\django\core\management\base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "C:\Python\Python38\lib\site-packages\django\core\management\commands\migrate.py", line 231, in handle
    post_migrate_state = executor.migrate(
  File "C:\Python\Python38\lib\site-packages\django\db\migrations\executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "C:\Python\Python38\lib\site-packages\django\db\migrations\executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "C:\Python\Python38\lib\site-packages\django\db\migrations\executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "C:\Python\Python38\lib\site-packages\django\db\migrations\migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "C:\Python\Python38\lib\site-packages\django\db\migrations\operations\fields.py", line 110, in database_forwards
    schema_editor.add_field(
  File "C:\Python\Python38\lib\site-packages\django\db\backends\sqlite3\schema.py", line 328, in add_field
    self._remake_table(model, create_field=field)
  File "C:\Python\Python38\lib\site-packages\django\db\backends\sqlite3\schema.py", line 189, in _remake_table
    self.effective_default(create_field)
  File "C:\Python\Python38\lib\site-packages\django\db\backends\base\schema.py", line 303, in effective_default
    return field.get_db_prep_save(self._effective_default(field), self.connection)
  File "C:\Python\Python38\lib\site-packages\django\db\models\fields\__init__.py", line 821, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "C:\Python\Python38\lib\site-packages\django\db\models\fields\__init__.py", line 1376, in get_db_prep_value
    value = self.get_prep_value(value)
  File "C:\Python\Python38\lib\site-packages\django\db\models\fields\__init__.py", line 1355, in get_prep_value
    value = super().get_prep_value(value)
  File "C:\Python\Python38\lib\site-packages\django\db\models\fields\__init__.py", line 1215, in get_prep_value
    return self.to_python(value)
  File "C:\Python\Python38\lib\site-packages\django\db\models\fields\__init__.py", line 1316, in to_python
    parsed = parse_datetime(value)
  File "C:\Python\Python38\lib\site-packages\django\utils\dateparse.py", line 107, in parse_datetime
    match = datetime_re.match(value)
TypeError: expected string or bytes-like object`
```

```python
from django.db import models

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=50)


class Unit(models.Model):
    unit = models.ForeignKey(Category, on_delete=models.PROTECT)


class List(models.Model):
    list_item = models.IntegerField()
    list_list = models.CharField(max_length=100)
    list_per_unit = models.IntegerField()
    list_total = models.IntegerField()
    list_remark = models.CharField(max_length=255)
    list_date = models.DateTimeField(auto_now_add=True)
    list_category = models.ForeignKey(Category, on_delete=models.PROTECT)
```

สามตารางสุดท้ายมัน create ไม่ได้

**Comment by tanin-t** [comment]
เพิ่มกำลังใน database หมายถึงอะไรครับ?

**Comment by tanin-t** [comment]
ใช้ code block แบบนี้ด้วยครับเวลาจะใส่ code เข้ามา

\`\`\`python
class Category(models.Model):
&nbsp;&nbsp;&nbsp;&nbsp;name = models.CharField(max_length=50)
\`\`\`

จะได้แบบนี้
```python
class Category(models.Model):
    name = models.CharField(max_length=50)
```

**Comment by tanin-t** [comment]
ขอดูไฟล์ `bill/migrations/0007_auto_20210422_0041.py` หน่อยครับปัญหาน่าจะเกิดจากไฟล์นี้

**Comment by yoghurtpowerbear** [comment]
```python
# Generated by Django 3.0.5 on 2021-04-21 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0006_auto_20210421_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='list_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bill.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='list_date',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='list_remark',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
```

**Comment by tanin-t** [comment]
![IMG_0005](https://user-images.githubusercontent.com/15776810/115760973-0788e500-a3cc-11eb-8b04-cfe93e595172.jpeg)

ปัญหาเกิดจาก เราพยายามจะสร้างฟีลที่เป็นประเภท DateTime แต่เราให้ค่า default มันเป็น integer

**Comment by tanin-t** [comment]
เนื่องจากเราทำการเพิ่มฟีลใหม่เข้าไปใน model ที่อาจจะมีข้อมูลอยู่แล้ว django จึงจะถามว่า "สำหรับข้อมูลเก่า ฟีลใหม่พวกนี้จะให้ใส่ค่าเป็นอะไรดี" ถ้าเราเลือกข้อมูลผิดประเภทมันก็จะทำให้ migrate ไม่ผ่านได้

วิธีการแก้คือ
1. ลบไฟล์ 0007_auto_20210422_0041.py ออกไปก่อน
2. แก้ไขไฟล์ `models.py` ดังนี้
```python
class List(models.Model):
    list_item = models.IntegerField()
    list_list = models.CharField(max_length=100)
    list_per_unit = models.IntegerField()
    list_total = models.IntegerField()
    list_remark = models.CharField(max_length=255, default='') # แก้บรรทัดนี้
    list_date = models.DateTimeField(auto_now_add=True)
    list_category = models.ForeignKey(Category, on_delete=models.PROTECT, null=True) # แก้บรรทัดนี้
```
สองบรรทัดที่ให้แก้ไปด้านบนคือ เรากำหนดค่า default สำหรับทั้งข้อมูลเก่าและข้อมูลใหม่ ส่วนตัว `list_date` เราจะใช้วิธี one-time default ที่จะอธิบายในข้อต่อไป

3. รันคำสั่ง `python manage.py makemigrations` ใหม่อีกรอบ ให้เราเลือก one-time off default ซี่งเป็นการกำหนดค่า default สำหรับข้อมูลเก่าที่มีอยู่ใน database อยู่แล้ว แต่จะไม่เกี่ยวข้องกับข้อมูลของใหม่
4. เวลา django ถามหาค่า default ของ `list_date` ให้พิมพ์ `timezone.now`
5. `python manage.py migrate` ก็จะใช้งานได้

**Comment by yoghurtpowerbear** [comment]
มันไม่ถามครับ

**Comment by tanin-t** [comment]
แล้วได้มั้ยครับ?

**Comment by yoghurtpowerbear** [comment]
ยังครับ

**Comment by yoghurtpowerbear** [comment]
This is an error 
```
PS C:\Users\HP\OneDrive\Documents\django-joey\mysite> py manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Python\Python38\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Python\Python38\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Python\Python38\lib\site-packages\django\core\management\base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Python\Python38\lib\site-packages\django\core\management\base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "C:\Python\Python38\lib\site-packages\django\core\management\base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "C:\Python\Python38\lib\site-packages\django\core\management\commands\migrate.py", line 86, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "C:\Python\Python38\lib\site-packages\django\db\migrations\executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "C:\Python\Python38\lib\site-packages\django\db\migrations\loader.py", line 49, in __init__
    self.build_graph()
  File "C:\Python\Python38\lib\site-packages\django\db\migrations\loader.py", line 274, in build_graph
    raise exc
  File "C:\Python\Python38\lib\site-packages\django\db\migrations\loader.py", line 248, in build_graph
    self.graph.validate_consistency()
  File "C:\Python\Python38\lib\site-packages\django\db\migrations\graph.py", line 195, in validate_consistency
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "C:\Python\Python38\lib\site-packages\django\db\migrations\graph.py", line 195, in <listcomp>
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "C:\Python\Python38\lib\site-packages\django\db\migrations\graph.py", line 58, in raise_error
    raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
django.db.migrations.exceptions.NodeNotFoundError: Migration bill.0008_auto_20210422_0043 dependencies reference nonexistent parent node ('bill', '0007_auto_20210422_0041')
```

**Comment by tanin-t** [comment]
ต้องลบ `0008_auto_20210422_0043.py` ออกด้วยครับ
ไฟล์ `0008_auto_20210422_0043.py` มันใช้ไฟล์ `0007_auto_20210422_0041.py` พอลบออกไปมันเลยหาไม่เจอ

**Comment by yoghurtpowerbear** [comment]
Thank you so much

**Comment by yoghurtpowerbear** [comment]
ยังทำไม่ได้ครับ
